// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDezVUkiYPkzyubGbZdZ-Y1kGHVr63qR6w',
    appId: '1:320737047269:web:357af408fea7d934aa5a0c',
    messagingSenderId: '320737047269',
    projectId: 'reco-genie',
    authDomain: 'reco-genie.firebaseapp.com',
    storageBucket: 'reco-genie.firebasestorage.app',
    measurementId: 'G-EPTPGHZF67',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7QvRMQca5Hy4HyH9NoV41CYgZQoQE58Q',
    appId: '1:320737047269:android:1993e8beec68ff80aa5a0c',
    messagingSenderId: '320737047269',
    projectId: 'reco-genie',
    storageBucket: 'reco-genie.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_9JTlvvlqMasEbgHricPttFmvqEf-uF8',
    appId: '1:320737047269:ios:b6da406415672638aa5a0c',
    messagingSenderId: '320737047269',
    projectId: 'reco-genie',
    storageBucket: 'reco-genie.firebasestorage.app',
    iosBundleId: 'com.example.recoGenieTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_9JTlvvlqMasEbgHricPttFmvqEf-uF8',
    appId: '1:320737047269:ios:b6da406415672638aa5a0c',
    messagingSenderId: '320737047269',
    projectId: 'reco-genie',
    storageBucket: 'reco-genie.firebasestorage.app',
    iosBundleId: 'com.example.recoGenieTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDezVUkiYPkzyubGbZdZ-Y1kGHVr63qR6w',
    appId: '1:320737047269:web:f030449481bc2c60aa5a0c',
    messagingSenderId: '320737047269',
    projectId: 'reco-genie',
    authDomain: 'reco-genie.firebaseapp.com',
    storageBucket: 'reco-genie.firebasestorage.app',
    measurementId: 'G-X6BL08WHS5',
  );
}
